version: '3.9'

services:
  web:
    build: .
    network_mode: host
    container_name: amd-train
    restart: always
    volumes:
      - "/stor:/stor"
    environment:
      APP_PORT: '8088'
      LOGGER_DIR: '/stor/data/logs/amd-train/'
      FILE_DIR: '/stor/data/amd-train/'
      SQLALCHEMY_DATABASE_URI: 'mysql://root:root@127.0.0.1/amd_train'
      USER_DEFAULT_PASSWORD: ''

  worker:
    build: .
    entrypoint: ["arq", "utility.arq_worker.WorkerSettings"]
    network_mode: host
    container_name: amd-train-worker
    restart: always
    volumes:
      - "/stor:/stor"

  tensorboard:
    build: .
    entrypoint: ["tensorboard", "--logdir", "/stor/data/amd-train", "--host", "0.0.0.0", "--port", "8089"]
    network_mode: host
    container_name: amd-train-tensorboard
    restart: always
    volumes:
      - "/stor:/stor"